Repository Team-Zetta/Zetta, pull requests merged in 2018-03, with the labels that each got.

#43 tried to float the arrows
  common/main.css
  images/2placeholder-16by9.svg
  index.html
Labels: dev

#45 added bg image, icons, and made all text roboto
  common/main.css
  common/modules.css
  images/arrow.svg
  images/bg-1.jpg
  images/bg-2.jpg
  images/bg-3.jpg
  images/location-icon.svg
  index.html
Labels: design, enhancement

#46 darkenned bg image
  images/bg-1.jpg
Labels: enhancement

#50 deleted unnecessary assets
  images/2placeholder-16by9.svg
  images/bg-2.jpg
  images/bg-3.jpg
  images/placeholder-16by9.svg
  images/placeholder-circle.svg
Labels: content

#59 fixed tempurature btn border problem
  common/main.css
  patterns/buttons/buttons.css
Labels: dev

#77 half done Radio buttons
  common/main.css
  index.html
Labels: bug, dev

#79 added hover transitions
  common/main.css
  patterns/buttons/buttons.css
Labels: enhancement
